### PR TITLE
Add linter to project

### PR DESCRIPTION
**Pull request by tiago154**
**What was done?**

- Adds eslint support to the project
- Script creation that validates lint and fixes simpler cases - `npm run lint` & `npm run lint:fix`

#4

### CODE REVIEW

**Comment by tiago154** [comment]
Hello, I'm participating in the hacktoberfest.
If you can add the `hacktoberfest-accepted` label to this PR I would be grateful 😄

**Comment by staranbeer** [comment]
Hey @tiago154
Thank you for your contribution to the project. Did you try running `npm run build`. It looks like It need some overrides to work properly. will you be will to look into it? 

Also I've added the `hacktoberfest` tag.

**Comment by staranbeer** [comment]
@tiago154 The previous pull changed all instances of function declarations to arrow functions. I think arrow functions should be better for this project and an override should be used to make sure linter does'nt flag the arrow function syntax

**Comment by tiago154** [comment]
Hello @staranbeer .

I needed to apply some fixes that lint was breaking so I had to change a lot of files.
I validated the arrow function issue and already made the adjustment in the files and in the lint rule

I also validated the build and execution of the project and everything seems to be ok now.
Let me know if you find anything incorrect or have questions.

**Comment by staranbeer** [comment]
@tiago154  Thanks a lot for contributing to this project. I've merged your pull request, please consider starring this project if you liked it :smile:

**Comment by tiago154** [comment]
Hello @staranbeer , the only thing missing is to add the `hacktoberfest-accepted` label to this pull request, so that it helps me to count in the event. I'll be thankful.

**Comment by staranbeer** [comment]
@tiago154  done! :smile:

**Pull request merged**
